FROM golang:1.24.6-alpine

ENV GOBIN /go/bin

RUN mkdir -p /app /src/scheduler-for-ocf
ADD . /src/scheduler-for-ocf
WORKDIR /src/scheduler-for-ocf

RUN apk add --no-cache git bash vim gcc g++ make curl

RUN go mod download

RUN go build -o /app/cf-api github.com/cloudfoundry-community/ocf-scheduler/cmd/jecfapi

EXPOSE 8002

CMD ["/app/cf-api", "8002"]
