#!/bin/bash
# vim:et:ts=2:sts=2:sw=2
set -ue

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
test -n "${APP_NAME:-}" || bail "GIT_CI must be set to the path of the git repo containing the CI assets."

# Start safe
safe local --memory &
safe_pid=$!
sleep 5
while ! safe status &>/dev/null ; do sleep 2 ; done
sleep 2
echo ""

# Get safe config
SAFE_TOKEN=$(safe vault token lookup --format json | jq -r '.data.id')
export SAFE_TOKEN

# build required certs (including doomsday's)
header "Building certificates..."

echo " - secret/dd/ssl"
safe x509 issue -t 2y -n 127.0.0.1 -n localhost -n doomsday secret/dd/ssl
echo " - secret/test/expired"
safe x509 issue -t 0d -n 127.0.0.1 -n localhost -n doomsday secret/test/expired
echo " - secret/test/soon"
safe x509 issue -t 4h -n 127.0.0.1 -n localhost -n doomsday secret/test/soon
echo " - secret/test/next"
safe x509 issue -t 2d -n 127.0.0.1 -n localhost -n doomsday secret/test/next
echo " - secret/test/fortnight"
safe x509 issue -t 14d -n 127.0.0.1 -n localhost -n doomsday secret/test/fortnight

header "Starting doomsday server"
# Build doomsday server config
safe targets --json | \
  jq '.[0] | {"meta": .}' | \
  spruce merge $GIT_CI/ci/ddconfig.yml - \
  > /root/.ddconfig

# Start doomsday server and capture pid
export DDCMD="${DDCMD:=build/doomsday-linux-amd64}"
$DDCMD server -m ~/.ddconfig  &> ~/dd.log &
dd_pid=$!

# target and login
sleep 5
$DDCMD target dd https://localhost -k
$DDCMD login -u admin -p password

# refresh
$DDCMD refresh

header "Testing the certificates"

# list
$DDCMD list | $GIT_CI/ci/scripts/test_list
test_list=$?

# 
$DDCMD dashboard | $GIT_CI/ci/scripts/test_dashboard
test_dashboard=$?

# cleanup
kill $dd_pid
kill -9 $(pgrep -P $safe_pid) $safe_pid # need to kill vault and safe explicitly

echo
echo "================================================================================"
if [ $((test_list || test_dashboard)) -eq 0 ] ; then
  echo "SUCCESS!"
  exit 0
else
  echo "FAILURE!"
  exit 1
fi
