jobs:
- name: build
  public: true
  serial: false
  plan:
  - in_parallel:
    - { get: version, params: {pre: rc} }
    - { get: git, trigger: true }
    - { get: git-ci }
  - task: build
    file: git-ci/ci/tasks/build.yml
    params:
      APP_NAME:      (( grab meta.app_name || meta.name ))
      MODULE:        (( grab meta.go.module ))
      CMD_PATH:      (( grab meta.go.cmd_path ))
      STATIC_BINARY: (( grab meta.go.force_static_binary ))
  - in_parallel:
    - put: build-linux-amd64
      params:
        file: build/*-linux-amd64-*.tar.gz
        acl: public-read
    - put: build-linux-arm64
      params:
        file: build/*-linux-arm64-*.tar.gz
        acl: public-read
    - put: build-darwin-amd64
      params:
        file: build/*-darwin-amd64-*.tar.gz
        acl: public-read
    - put: build-darwin-arm64
      params:
        file: build/*-darwin-arm64-*.tar.gz
        acl: public-read
    - put: build-cache
      params:
        file: build/*-cache-*.tar.gz
        acl: public-read
  - put: version
    params: {file: version/number}

  on_failure:
    put: notify
    params:
      username: (( grab meta.slack.username ))
      icon_url: (( grab meta.slack.icon ))
      text:    '(( concat meta.slack.fail_url " " meta.pipeline ": test job failed" ))'
